import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const M=['Today','Mood','Sleep','Exercise','Sessions','Discuss','First Aid','Homework','Skills','Safety','Journal','Privacy'];
const storeKey='mm-client-v3';
function load(){try{return JSON.parse(localStorage.getItem(storeKey))||{}}catch{return{}}}
function save(v){localStorage.setItem(storeKey,JSON.stringify(v))}
const now=()=>new Date().toISOString();
function App(){const[view,setView]=useState('Today');const[data,setData]=useState(load);const[state,setState]=useState('Green');const[toast,setToast]=useState('');const patch=(k,v)=>setData(d=>{const n={...d,[k]:v};save(n);return n});const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2600)};return <div className={'app '+state.toLowerCase()}><header><div className="brand"><div className="seal">MM</div><div><b>Mood &amp; Mind</b><small>Client Companion</small></div></div><div className="state"><span>How I am</span>{['Green','Yellow','Red','Recovery'].map(x=><button key={x} className={state===x?'on':''} onClick={()=>setState(x)}>{x}</button>)}</div></header><aside>{M.map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x}</button>)}</aside><main>{toast&&<div className="toast">{toast}</div>}<Hero state={state}/><Page view={view} data={data} patch={patch} notify={notify} setView={setView}/></main><nav className="mobile">{['Today','Discuss','Safety','Journal'].map(x=><button onClick={()=>setView(x)} key={x}>{x}</button>)}</nav></div>}
function Hero({state}){return <section className="hero"><div><small>MOOD &amp; MIND CENTRE</small><h1>{state==='Red'?'Safety first':state==='Recovery'?'Gentle recovery':'Your space between sessions'}</h1><p>{state==='Red'?'Keep this simple. Use your safety plan, contact support, or call 000 if there is immediate danger.':'Track what matters, save things for therapy, practise skills and keep your safety plan close.'}</p></div><div className="gigi">Gigi<span>calm support</span></div></section>}
function Page(p){switch(p.view){case'Today':return <Today {...p}/>;case'Mood':return <Tracker title="Mood tracker" fields={['Mood /10','Main feeling','Trigger or context','What helped']} name="mood" {...p}/>;case'Sleep':return <Tracker title="Sleep tracker" fields={['Bed time','Wake time','Hours slept','Sleep quality /10','Nightmares / waking']} name="sleep" {...p}/>;case'Exercise':return <Tracker title="Exercise & activity" fields={['Activity','Minutes','Effort /10','How I felt afterwards']} name="exercise" {...p}/>;case'Sessions':return <Sessions {...p}/>;case'Discuss':return <ListPad title="Things to discuss with my therapist" name="discuss" placeholder="Add something while it is fresh…" {...p}/>;case'First Aid':return <FirstAid {...p}/>;case'Homework':return <ListPad title="Homework" name="homework" placeholder="Add homework or a task from therapy…" {...p}/>;case'Skills':return <Skills {...p}/>;case'Safety':return <Safety {...p}/>;case'Journal':return <Journal {...p}/>;case'Privacy':return <Privacy/>;default:return null}}
function Card({title,children,className=''}){return <section className={'card '+className}><h2>{title}</h2>{children}</section>}
function Today({data,setView}){return <><div className="grid4"><Metric label="Mood" value={data.mood?.slice(-1)[0]?.values?.[0]||'—'} go={()=>setView('Mood')}/><Metric label="Sleep" value={data.sleep?.slice(-1)[0]?.values?.[2]||'—'} go={()=>setView('Sleep')}/><Metric label="Activity" value={data.exercise?.slice(-1)[0]?.values?.[0]||'—'} go={()=>setView('Exercise')}/><Metric label="Discuss" value={(data.discuss||[]).length} go={()=>setView('Discuss')}/></div><div className="two"><Card title="Next therapy step"><p>Keep notes for your next session, complete homework and practise one useful skill rather than trying to do everything at once.</p><button onClick={()=>setView('Discuss')} className="primary">Add something for therapy</button></Card><Card title="Safety always available"><p>Your safety plan and support contacts stay one tap away.</p><button onClick={()=>setView('Safety')} className="danger">Open safety</button></Card></div></>}
function Metric({label,value,go}){return <button className="metric" onClick={go}><span>{label}</span><b>{value}</b></button>}
function Tracker({title,fields,name,data,patch,notify}){const[v,setV]=useState(fields.map(()=>''));const rows=data[name]||[];return <Card title={title}><div className="form">{fields.map((f,i)=><label key={f}>{f}<input value={v[i]} onChange={e=>setV(a=>a.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div><button className="primary" onClick={()=>{if(!v.some(Boolean))return;patch(name,[...rows,{at:now(),values:v}]);setV(fields.map(()=>''));notify('Saved privately on this device')}}>Save entry</button><History rows={rows}/></Card>}
function History({rows}){if(!rows.length)return <p className="muted">No entries yet.</p>;return <div className="history">{rows.slice(-5).reverse().map((r,i)=><div key={i}><small>{new Date(r.at).toLocaleString('en-AU')}</small><span>{r.values.filter(Boolean).join(' · ')}</span></div>)}</div>}
function ListPad({title,name,placeholder,data,patch,notify}){const[t,setT]=useState('');const rows=data[name]||[];return <Card title={title}><div className="addrow"><input value={t} placeholder={placeholder} onChange={e=>setT(e.target.value)}/><button className="primary" onClick={()=>{if(!t.trim())return;patch(name,[...rows,{text:t.trim(),at:now(),done:false}]);setT('');notify('Saved')}}>Add</button></div><div className="list">{rows.map((r,i)=><label key={i}><input type="checkbox" checked={!!r.done} onChange={e=>patch(name,rows.map((x,j)=>j===i?{...x,done:e.target.checked}:x))}/><span>{r.text}</span><button onClick={()=>patch(name,rows.filter((_,j)=>j!==i))}>×</button></label>)}</div></Card>}
function Sessions({data,patch,notify}){const rows=data.sessions||[];const[reason,setReason]=useState('');return <Card title="Session cancelled / changed"><p>Record a cancellation without putting clinical detail here. Use reception for actual rebooking.</p><div className="addrow"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Optional note for myself"/><button className="primary" onClick={()=>{patch('sessions',[...rows,{at:now(),reason}]);setReason('');notify('Cancellation note saved')}}>Record cancellation</button></div><History rows={rows.map(x=>({at:x.at,values:[x.reason||'Session cancelled']}))}/></Card>}
function FirstAid(){return <Card title="Dissociation first-aid kit" className="calm"><div className="steps"><b>1. Orient</b><p>Say your name, today’s date and where you are. Look for five things you can see.</p><b>2. Ground</b><p>Feel your feet, hold something cool or textured, and notice three sounds around you.</p><b>3. Reduce demand</b><p>Use short sentences. Sit somewhere safer and quieter if you can.</p><b>4. Connect</b><p>Use your safety plan or contact a trusted support person if you need help.</p></div></Card>}
function Skills({data,patch,notify}){const skills=['5-4-3-2-1 grounding','Name the feeling','Slow the pace','Ask for a pause','One small next step','Recovery routine'];const rows=data.skills||{};return <Card title="Skills building"><div className="skills">{skills.map(s=><button key={s} className={rows[s]?'done':''} onClick={()=>{patch('skills',{...rows,[s]:!rows[s]});notify(rows[s]?'Marked for more practice':'Practice recorded')}}><b>{s}</b><span>{rows[s]?'Practised':'Tap after practising'}</span></button>)}</div></Card>}
function Safety({data,patch,notify}){const plan=data.safety||{warning:'',self:'',people:'',professional:'',safePlace:'',anchors:''};const upd=(k,v)=>patch('safety',{...plan,[k]:v});return <><Card title="Safety plan" className="safety"><p className="important">This app does not diagnose risk and does not silently contact anyone. If there is immediate danger, call 000.</p><div className="form">{[['warning','My warning signs'],['self','Things I can do myself'],['safePlace','Safer places'],['people','People I can contact'],['professional','Professional / clinic contacts'],['anchors','Reasons or anchors for getting through this']].map(([k,l])=><label key={k}>{l}<textarea value={plan[k]} onChange={e=>upd(k,e.target.value)}/></label>)}</div><button className="primary" onClick={()=>notify('Safety plan saved')}>Save safety plan</button></Card><div className="emergency"><a href="tel:000">Call 000</a><a href="tel:131114">Lifeline 13 11 14</a><a href="tel:+61755732200">Mood &amp; Mind 07 5573 2200</a></div></>}
function Journal({data,patch,notify}){const[t,setT]=useState('');const rows=data.journal||[];return <Card title="Journal"><p>Your journal is private by default. Mark an entry “bring to therapy” only when you choose.</p><textarea className="journal" value={t} onChange={e=>setT(e.target.value)} placeholder="Write here…"/><button className="primary" onClick={()=>{if(!t.trim())return;patch('journal',[...rows,{text:t.trim(),at:now(),share:false}]);setT('');notify('Journal entry saved privately')}}>Save private entry</button><div className="journalRows">{rows.slice().reverse().map((r,ri)=>{const i=rows.length-1-ri;return <article key={i}><small>{new Date(r.at).toLocaleString('en-AU')}</small><p>{r.text}</p><label><input type="checkbox" checked={r.share} onChange={e=>patch('journal',rows.map((x,j)=>j===i?{...x,share:e.target.checked}:x))}/> Bring this to therapy</label></article>})}</div></Card>}
function Privacy(){return <Card title="Privacy & sharing"><p><b>Private by default.</b> Tracking, discussion notes and journal entries stay private unless a future connected feature clearly asks you to share them.</p><p>No generative AI is allowed to decide that you are safe, unsafe, or to silently contact a support person or emergency services. Safety actions must be explicit, visible and auditable.</p><p>Before real client use, Irene’s practice should approve the clinical wording, privacy notice, retention settings and emergency workflow.</p></Card>}
createRoot(document.getElementById('root')).render(<App/>);
