import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
import{createWellbeingEntry,getCurrentSession,listWellbeingEntries,loadSafetyPlan,recordSafetyEvent,saveSafetyPlan,signInWithEmail,signOut,signUpWithEmail}from'./neon.js';

const M=['Today','Mood','Sleep','Exercise','Sessions','Discuss','First Aid','Homework','Skills','Safety','Journal','Privacy'];
const now=()=>new Date().toISOString();

function App(){
 const[session,setSession]=useState(undefined);const[view,setView]=useState('Today');const[data,setData]=useState({});const[state,setState]=useState('Green');const[toast,setToast]=useState('');const[busy,setBusy]=useState(false);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2800)};
 useEffect(()=>{getCurrentSession().then(setSession).catch(()=>setSession(null))},[]);
 useEffect(()=>{if(!session?.user)return;setBusy(true);Promise.all([listWellbeingEntries(),loadSafetyPlan()]).then(([rows,plan])=>{const grouped={};for(const r of rows){const k=r.entry_type==='session_cancelled'?'sessions':r.entry_type==='skill'?'skills':r.entry_type;grouped[k]=[...(grouped[k]||[]),{...r.payload,at:r.created_at,dbId:r.id,share:r.shared_with_clinician}]};if(plan)grouped.safety={warning:plan.warning_signs||'',self:plan.self_actions||'',safePlace:plan.safe_places||'',people:plan.support_people||'',professional:plan.professional_contacts||'',anchors:plan.anchors||''};setData(grouped)}).catch(e=>notify(e.message||'Could not load your records')).finally(()=>setBusy(false))},[session?.user?.id]);
 if(session===undefined)return <div className="loading-screen">Opening Mood &amp; Mind…</div>;
 if(!session?.user)return <AuthScreen onSession={setSession}/>;
 const addEntry=async(type,payload,shared=false)=>{setBusy(true);try{const row=await createWellbeingEntry(type,payload,shared);const key=type==='session_cancelled'?'sessions':type==='skill'?'skills':type;setData(d=>({...d,[key]:[...(d[key]||[]),{...payload,at:row?.created_at||now(),dbId:row?.id,share:shared}]}));notify('Saved securely')}finally{setBusy(false)}};
 return <div className={'app '+state.toLowerCase()}><header><div className="brand"><div className="seal">MM</div><div><b>Mood &amp; Mind</b><small>Client Companion</small></div></div><div className="state"><span>How I am</span>{['Green','Yellow','Red','Recovery'].map(x=><button key={x} className={state===x?'on':''} onClick={()=>setState(x)}>{x}</button>)}</div><button className="signout" onClick={async()=>{await signOut();setSession(null)}}>Sign out</button></header><aside>{M.map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x}</button>)}</aside><main>{toast&&<div className="toast">{toast}</div>}{busy&&<div className="syncbar">Securely syncing…</div>}<Hero state={state}/><Page view={view} data={data} setData={setData} notify={notify} setView={setView} addEntry={addEntry}/></main><nav className="mobile">{['Today','Discuss','Safety','Journal'].map(x=><button onClick={()=>setView(x)} key={x}>{x}</button>)}</nav></div>
}

function AuthScreen({onSession}){const[mode,setMode]=useState('signin');const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='signup')await signUpWithEmail(name,email,password);else await signInWithEmail(email,password);const s=await getCurrentSession();if(!s?.user)throw new Error('Sign-in did not complete.');onSession(s)}catch(e){setError(e.message||'Unable to sign in')}finally{setBusy(false)}};return <div className="auth-shell"><section className="auth-card"><div className="seal large">MM</div><small>MOOD &amp; MIND CENTRE</small><h1>{mode==='signin'?'Welcome back':'Create your private account'}</h1><p>Your wellbeing records are protected by your individual sign-in.</p><form onSubmit={submit}>{mode==='signup'&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input required minLength="8" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signin'?'current-password':'new-password'}/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button></form><button className="linkbtn" onClick={()=>{setError('');setMode(mode==='signin'?'signup':'signin')}}>{mode==='signin'?'New client? Create account':'Already have an account? Sign in'}</button></section></div>}
function Hero({state}){return <section className="hero"><div><small>MOOD &amp; MIND CENTRE</small><h1>{state==='Red'?'Safety first':state==='Recovery'?'Gentle recovery':'Your space between sessions'}</h1><p>{state==='Red'?'Keep this simple. Use your safety plan, contact support, or call 000 if there is immediate danger.':'Track what matters, save things for therapy, practise skills and keep your safety plan close.'}</p></div><div className="gigi">Gigi<span>calm support</span></div></section>}
function Page(p){switch(p.view){case'Today':return <Today {...p}/>;case'Mood':return <Tracker title="Mood tracker" fields={['Mood /10','Main feeling','Trigger or context','What helped']} name="mood" {...p}/>;case'Sleep':return <Tracker title="Sleep tracker" fields={['Bed time','Wake time','Hours slept','Sleep quality /10','Nightmares / waking']} name="sleep" {...p}/>;case'Exercise':return <Tracker title="Exercise & activity" fields={['Activity','Minutes','Effort /10','How I felt afterwards']} name="exercise" {...p}/>;case'Sessions':return <Sessions {...p}/>;case'Discuss':return <ListPad title="Things to discuss with my therapist" name="discuss" placeholder="Add something while it is fresh…" {...p}/>;case'First Aid':return <FirstAid/>;case'Homework':return <ListPad title="Homework" name="homework" placeholder="Add homework or a task from therapy…" {...p}/>;case'Skills':return <Skills {...p}/>;case'Safety':return <Safety {...p}/>;case'Journal':return <Journal {...p}/>;case'Privacy':return <Privacy/>;default:return null}}
function Card({title,children,className=''}){return <section className={'card '+className}><h2>{title}</h2>{children}</section>}
function Today({data,setView}){return <><div className="grid4"><Metric label="Mood" value={data.mood?.slice(-1)[0]?.values?.[0]||'—'} go={()=>setView('Mood')}/><Metric label="Sleep" value={data.sleep?.slice(-1)[0]?.values?.[2]||'—'} go={()=>setView('Sleep')}/><Metric label="Activity" value={data.exercise?.slice(-1)[0]?.values?.[0]||'—'} go={()=>setView('Exercise')}/><Metric label="Discuss" value={(data.discuss||[]).length} go={()=>setView('Discuss')}/></div><div className="two"><Card title="Next therapy step"><p>Keep notes for your next session, complete homework and practise one useful skill rather than trying to do everything at once.</p><button onClick={()=>setView('Discuss')} className="primary">Add something for therapy</button></Card><Card title="Safety always available"><p>Your safety plan and support contacts stay one tap away.</p><button onClick={()=>setView('Safety')} className="danger">Open safety</button></Card></div></>}
function Metric({label,value,go}){return <button className="metric" onClick={go}><span>{label}</span><b>{value}</b></button>}
function Tracker({title,fields,name,data,addEntry}){const[v,setV]=useState(fields.map(()=>''));const rows=data[name]||[];return <Card title={title}><div className="form">{fields.map((f,i)=><label key={f}>{f}<input value={v[i]} onChange={e=>setV(a=>a.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div><button className="primary" onClick={async()=>{if(!v.some(Boolean))return;await addEntry(name,{values:v});setV(fields.map(()=>''))}}>Save entry</button><History rows={rows}/></Card>}
function History({rows}){if(!rows.length)return <p className="muted">No entries yet.</p>;return <div className="history">{rows.slice(-5).reverse().map((r,i)=><div key={r.dbId||i}><small>{new Date(r.at).toLocaleString('en-AU')}</small><span>{(r.values||[r.text]).filter(Boolean).join(' · ')}</span></div>)}</div>}
function ListPad({title,name,placeholder,data,addEntry}){const[t,setT]=useState('');const rows=data[name]||[];return <Card title={title}><div className="addrow"><input value={t} placeholder={placeholder} onChange={e=>setT(e.target.value)}/><button className="primary" onClick={async()=>{if(!t.trim())return;await addEntry(name,{text:t.trim(),done:false});setT('')}}>Add</button></div><div className="list">{rows.map((r,i)=><label key={r.dbId||i}><span>{r.text}</span></label>)}</div></Card>}
function Sessions({data,addEntry}){const rows=data.sessions||[];const[reason,setReason]=useState('');return <Card title="Session cancelled / changed"><p>Record a cancellation without putting clinical detail here. Use reception for actual rebooking.</p><div className="addrow"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Optional note for myself"/><button className="primary" onClick={async()=>{await addEntry('session_cancelled',{reason});setReason('')}}>Record cancellation</button></div><History rows={rows.map(x=>({...x,values:[x.reason||'Session cancelled']}))}/></Card>}
function FirstAid(){return <Card title="Dissociation first-aid kit" className="calm"><div className="steps"><b>1. Orient</b><p>Say your name, today’s date and where you are. Look for five things you can see.</p><b>2. Ground</b><p>Feel your feet, hold something cool or textured, and notice three sounds around you.</p><b>3. Reduce demand</b><p>Use short sentences. Sit somewhere safer and quieter if you can.</p><b>4. Connect</b><p>Use your safety plan or contact a trusted support person if you need help.</p></div></Card>}
function Skills({data,addEntry}){const skills=['5-4-3-2-1 grounding','Name the feeling','Slow the pace','Ask for a pause','One small next step','Recovery routine'];const rows=data.skills||[];const practiced=useMemo(()=>new Set(rows.map(x=>x.name)),[rows]);return <Card title="Skills building"><div className="skills">{skills.map(s=><button key={s} className={practiced.has(s)?'done':''} onClick={()=>addEntry('skill',{name:s})}><b>{s}</b><span>{practiced.has(s)?'Practised':'Tap after practising'}</span></button>)}</div></Card>}
function Safety({data,setData,notify}){const plan=data.safety||{warning:'',self:'',people:'',professional:'',safePlace:'',anchors:''};const upd=(k,v)=>setData(d=>({...d,safety:{...plan,[k]:v}}));const persist=async()=>{await saveSafetyPlan({warning_signs:plan.warning,self_actions:plan.self,safe_places:plan.safePlace,support_people:plan.people,professional_contacts:plan.professional,anchors:plan.anchors});notify('Safety plan saved securely')};return <><Card title="Safety plan" className="safety"><p className="important">This app does not diagnose risk and does not silently contact anyone. If there is immediate danger, call 000.</p><div className="form">{[['warning','My warning signs'],['self','Things I can do myself'],['safePlace','Safer places'],['people','People I can contact'],['professional','Professional / clinic contacts'],['anchors','Reasons or anchors for getting through this']].map(([k,l])=><label key={k}>{l}<textarea value={plan[k]} onChange={e=>upd(k,e.target.value)}/></label>)}</div><button className="primary" onClick={persist}>Save safety plan</button></Card><div className="emergency"><a href="tel:000" onClick={()=>recordSafetyEvent('emergency_call_tapped','000')}>Call 000</a><a href="tel:131114" onClick={()=>recordSafetyEvent('crisis_line_tapped','Lifeline')}>Lifeline 13 11 14</a><a href="tel:+61755732200" onClick={()=>recordSafetyEvent('support_contact_requested','Mood & Mind')}>Mood &amp; Mind 07 5573 2200</a></div></>}
function Journal({data,addEntry}){const[t,setT]=useState('');const[share,setShare]=useState(false);const rows=data.journal||[];return <Card title="Journal"><p>Your journal is private by default. Choose “bring to therapy” only when you want to share that entry later.</p><textarea className="journal" value={t} onChange={e=>setT(e.target.value)} placeholder="Write here…"/><label className="sharecheck"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/> Bring this to therapy</label><button className="primary" onClick={async()=>{if(!t.trim())return;await addEntry('journal',{text:t.trim()},share);setT('');setShare(false)}}>Save entry</button><div className="journalRows">{rows.slice().reverse().map((r,i)=><article key={r.dbId||i}><small>{new Date(r.at).toLocaleString('en-AU')}</small><p>{r.text}</p><small>{r.share?'Marked to bring to therapy':'Private'}</small></article>)}</div></Card>}
function Privacy(){return <Card title="Privacy & sharing"><p><b>Private by default.</b> Your entries are tied to your individual account and protected in the database by per-user access rules.</p><p>No generative AI is allowed to decide that you are safe or unsafe, or silently contact a support person or emergency services. Safety actions are explicit and visible.</p><p>Before real-client rollout, the practice still needs to approve the final privacy notice, retention period and clinical emergency wording.</p></Card>}
createRoot(document.getElementById('root')).render(<App/>);
